image: python:3.8.2

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install black
          - pip install mypy
          - pip install flake8
          - pip install pylint
          - black --check .
          - mypy --strict .
          - flake8 .
          - pylint dlgis *.py
