
pipelines:
  default:
    - step:
        name: Tests
        image: iridl/dlgis_env:latest
        services:
          - postgres
        script:
          - ./bitbucket-pipeline-1.sh
          - pip install .
          - dlgis_import --help
          - dlgis_export --help
          - PGPASSWORD=postgres psql -U postgres -d postgres -h localhost -c 'select version();'

definitions:
  services:
    postgres:
      image: postgres:latest
      environment:
        POSTGRES_PASSWORD: postgres
